server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:h2:mem:userdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${USER_DB_USER:sa}
    password: ${USER_DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  flyway:
    enabled: true

paperflow:
  auth:
    jwtSecret: ${PF_JWT_SECRET:change-me-in-dev-change-me-in-dev-change-me}
    accessTokenTtlSeconds: ${PF_ACCESS_TTL:900}
    refreshTokenTtlSeconds: ${PF_REFRESH_TTL:2592000}

management:
  endpoints:
    web:
      exposure:
        include: health,info

